"""Application-wide constants for the drone fleet search system."""

# Service identification
SERVICE_NAME = "drone-fleet-search"
SERVICE_VERSION = "0.1.0"

# MQTT topic prefixes
MQTT_TOPIC_PREFIX = "drone-fleet"
MQTT_COMMAND_TOPIC = "command"
MQTT_TELEMETRY_TOPIC = "telemetry"
MQTT_IMAGE_TOPIC = "image"
MQTT_STATUS_TOPIC = "status"

# DynamoDB single-table design prefixes
PARTITION_KEY_MISSION = "MISSION#"
PARTITION_KEY_DRONE = "DRONE#"
PARTITION_KEY_ENVIRONMENT = "ENV#"
PARTITION_KEY_TEST = "TEST#"
PARTITION_KEY_DETECTION = "DETECTION#"

# S3 key prefixes
S3_PREFIX_IMAGES = "images/"
S3_PREFIX_ENVIRONMENTS = "environments/"
S3_PREFIX_DETECTIONS = "detections/"

# Application timeouts (seconds)
DEFAULT_LAMBDA_TIMEOUT = 30
API_REQUEST_TIMEOUT = 10
MAVLINK_HEARTBEAT_INTERVAL = 1
TELEMETRY_REPORT_INTERVAL = 2
IMAGE_UPLOAD_TIMEOUT = 30

# Fleet limits
MAX_FLEET_SIZE = 5
MAX_WAYPOINTS_PER_SEGMENT = 100
MAX_MISSION_DURATION_MINUTES = 120

# Edge obstacle avoidance
OBSTACLE_DETECTION_RANGE_METERS = 10.0
MINIMUM_CLEARANCE_METERS = 2.0
OBSTACLE_AVOIDANCE_LOOP_FREQUENCY_HZ = 10

# Image pipeline
IMAGE_CAPTURE_INTERVAL_SECONDS = 5
IMAGE_COMPRESSION_QUALITY = 85
MAX_IMAGE_SIZE_BYTES = 5_000_000

# S3 lifecycle retention (days)
RETENTION_DAYS_NON_MATCH = 7
RETENTION_DAYS_DISMISSED = 30
RETENTION_DAYS_UNREVIEWED = 90
RETENTION_DAYS_CONFIRMED = 365

# Fail-safe timeouts (seconds)
CONNECTIVITY_DEGRADED_THRESHOLD = 10
CONNECTIVITY_HOLDING_THRESHOLD = 30
CONNECTIVITY_RETURN_THRESHOLD = 120
